/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import BUS.CourseBUS;
import DTO.CourseDTO;
import DTO.DepartmentDTO;
import DTO.OnSiteCourseDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class DiaglogOnsiteCourse extends javax.swing.JDialog {
    CourseBUS courseBUS = new CourseBUS();
     HashMap<String, Integer> idMap;
     CourseDTO c;
     OnSiteCourseDTO c2;
     public int flag;
     int x;
     
    /**
     * Creates new form DiaglogOnsiteCourse
     */
    public DiaglogOnsiteCourse(int flag,CourseDTO c,OnSiteCourseDTO c2) throws SQLException {
        idMap = new HashMap<>();
        initComponents();
         addDataCombobox();
        setLocationRelativeTo(null);
        if(flag == 1){
            loadDataToUpdate(c,c2);
            x=flag;
        }
        
        btnXacNhan.addActionListener((e) -> {
            btnXacNhan_Click(c,c2);
            
            
        });
         btnHuy.addActionListener((e) -> {  
            setVisible(false);
        });
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfCredits = new javax.swing.JTextField();
        tfTitle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfLocation = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("THÊM KHÓA HỌC ONSITE");

        jLabel2.setText("Title");

        jLabel3.setText("Credits");

        jLabel4.setText("Department");

        jLabel6.setText("Location");

        btnXacNhan.setText("Xác Nhận");

        btnHuy.setText("Hủy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(199, 199, 199)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(74, 74, 74)
                                    .addComponent(tfCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(tfLocation))))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DiaglogOnsiteCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DiaglogOnsiteCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DiaglogOnsiteCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DiaglogOnsiteCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    DiaglogOnsiteCourse dialog = new DiaglogOnsiteCourse();
//                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                        @Override
//                        public void windowClosing(java.awt.event.WindowEvent e) {
//                            System.exit(0);
//                        }
//                    });
//                } catch (SQLException ex) {
//                    Logger.getLogger(DiaglogOnsiteCourse.class.getName()).log(Level.SEVERE, null, ex);
//                }
//               
//                
//            }
//        });
//    }
    public void btnXacNhan_Click(CourseDTO c,OnSiteCourseDTO c2){
        if (x == 1){
             updateCourse(c,c2);
                System.out.println("update");
         }
         else {
            System.out.println("add");
            addCourse();
        }
             
         
    }
    public void updateCourse(CourseDTO c,OnSiteCourseDTO c2){
        if(tfTitle.getText().isEmpty() || tfLocation.getText().isEmpty() || tfCredits.getText().isEmpty()){ 
             JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin!");
         }else {
             try {
             
             c.setTitle(tfTitle.getText());
             c.setCredits(Integer.parseInt(tfCredits.getText()));
             String departmentName = (String) jComboBox1.getSelectedItem();
             int departmentID = idMap.get(departmentName);
             c.setDepartmentID(departmentID);
             
             c2.setLocation(tfLocation.getText());
             courseBUS.updateCourse(c);
             courseBUS.updateOnsiteCourse(c2);
             
             setVisible(false);
         } catch (SQLException ex) {
             Logger.getLogger(DiaglogOnsiteCourse.class.getName()).log(Level.SEVERE, null, ex);
         }
         }
    }
    public void addCourse(){
        if(tfTitle.getText().isEmpty() || tfLocation.getText().isEmpty() || tfCredits.getText().isEmpty()){ 
             JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin!");
         }else {
             try {
             CourseDTO c = new CourseDTO();
             OnSiteCourseDTO c2 = new OnSiteCourseDTO();
             c.setTitle(tfTitle.getText());
             c.setCredits(Integer.parseInt(tfCredits.getText()));
             String departmentName = (String) jComboBox1.getSelectedItem();
             int departmentID = idMap.get(departmentName);
             c.setDepartmentID(departmentID);
             
             c2.setLocation(tfLocation.getText());
             courseBUS.insertCourseOnsite(c, c2);
             setVisible(false);
         } catch (SQLException ex) {
             Logger.getLogger(DiaglogOnsiteCourse.class.getName()).log(Level.SEVERE, null, ex);
         }
         }
    }
    public void addDataCombobox() throws SQLException{
        ArrayList<DepartmentDTO> list = new ArrayList();
        list = courseBUS.getDepartment();
        for (DepartmentDTO d : list) {
            jComboBox1.addItem(d.getName());
            idMap.put(d.getName(), d.getDepartmentID());
        }
    }
    public void loadDataToUpdate(CourseDTO c,OnSiteCourseDTO c2){
        jLabel1.setText("CẬP NHẬT KHÓA HỌC ONSITE");
        tfTitle.setText(c.getTitle());
        tfCredits.setText(c.getCredits()+"");
        jComboBox1.setSelectedItem(c.getDepartmentName());
        tfLocation.setText(c2.getLocation());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfCredits;
    private javax.swing.JTextField tfLocation;
    private javax.swing.JTextField tfTitle;
    // End of variables declaration//GEN-END:variables
}
