/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import BUS.CourseBUS;
import DTO.CourseDTO;
import DTO.DepartmentDTO;
import DTO.OnLineCourseDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class DialogOnlineCourse extends javax.swing.JDialog implements ActionListener{
     CourseBUS courseBUS = new CourseBUS();
     HashMap<String, Integer> idMap;
     CourseDTO c;
     OnLineCourseDTO c2;
     public int flag;
     int x;

     
    /**
     * Creates new form DialogOnlineCourse
     */
    public DialogOnlineCourse(int flag,CourseDTO c,OnLineCourseDTO c2) throws SQLException {
        idMap = new HashMap<>();
        initComponents();
        addDataCombobox();
        setLocationRelativeTo(null);
        if(flag == 1){
            loadDataToUpdate(c,c2);
            x = flag;
        }
        
        
        btnXacNhan.addActionListener((e) -> {
            btnXacNhan_Click(c,c2);
            
            
        });
         btnHuy.addActionListener((e) -> {  
            setVisible(false);
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        tfCredits = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfURL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("THÊM KHÓA HỌC ONLINE");

        jLabel2.setText("Title");

        jLabel3.setText("Credits");

        tfCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCreditsActionPerformed(evt);
            }
        });

        jLabel4.setText("Department");

        jLabel5.setText("URL");

        btnHuy.setText("Hủy");

        btnXacNhan.setText("Xác Nhận");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfURL, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfURL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCreditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCreditsActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogOnlineCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogOnlineCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogOnlineCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogOnlineCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    DialogOnlineCourse dialog = new DialogOnlineCourse();
//                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                        @Override
//                        public void windowClosing(java.awt.event.WindowEvent e) {
//                            System.exit(0);
//                        }
//                    });
//                } catch (SQLException ex) {
//                    Logger.getLogger(DialogOnlineCourse.class.getName()).log(Level.SEVERE, null, ex);
//                }
//               
//                 
//            }
//        });
//    }
    public void btnXacNhan_Click(CourseDTO c,OnLineCourseDTO c2){
         if (x == 1){
             
             updateCourse(c,c2);
         }
         else {
               
             addCourse();
         }
              
    }
    public void addCourse(){
        if(tfTitle.getText().isEmpty() || tfURL.getText().isEmpty() || tfCredits.getText().isEmpty()){ 
             JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin!");
         }else {
             try {
             CourseDTO c = new CourseDTO();
             OnLineCourseDTO c2 = new OnLineCourseDTO();
             c.setTitle(tfTitle.getText());
             c.setCredits(Integer.parseInt(tfCredits.getText()));
             String departmentName = (String) jComboBox1.getSelectedItem();
             int departmentID = idMap.get(departmentName);
             c.setDepartmentID(departmentID);
             
             c2.setUrl(tfURL.getText());
             courseBUS.insertCourseOnline(c, c2);
             setVisible(false);
         } catch (SQLException ex) {
             Logger.getLogger(DialogOnlineCourse.class.getName()).log(Level.SEVERE, null, ex);
         }
         }
    }
    public void updateCourse (CourseDTO c,OnLineCourseDTO c2){
        if(tfTitle.getText().isEmpty() || tfURL.getText().isEmpty() || tfCredits.getText().isEmpty()){ 
             JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin!");
         }else {
             try {
              
             c.setTitle(tfTitle.getText());
             c.setCredits(Integer.parseInt(tfCredits.getText()));
             String departmentName = (String) jComboBox1.getSelectedItem();
             int departmentID = idMap.get(departmentName);
             c.setDepartmentID(departmentID);
             
             c2.setUrl(tfURL.getText());
             courseBUS.updateCourse(c);
             courseBUS.updateOnlineCourse(c2);
             setVisible(false);
         } catch (SQLException ex) {
             Logger.getLogger(DialogOnlineCourse.class.getName()).log(Level.SEVERE, null, ex);
         }
         }
        
    }

    public void addDataCombobox() throws SQLException{
        ArrayList<DepartmentDTO> list = new ArrayList();
        list = courseBUS.getDepartment();
        for (DepartmentDTO d : list) {
            jComboBox1.addItem(d.getName());
            idMap.put(d.getName(), d.getDepartmentID());
        }
    }
    public void loadDataToUpdate(CourseDTO c,OnLineCourseDTO c2){
        jLabel1.setText("CẬP NHẬT KHÓA HỌC ONLINE" );
        tfTitle.setText(c.getTitle());
        tfCredits.setText(c.getCredits()+"");
        jComboBox1.setSelectedItem(c.getDepartmentName());
        tfURL.setText(c2.getUrl());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfCredits;
    private javax.swing.JTextField tfTitle;
    private javax.swing.JTextField tfURL;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
